version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "SonarQubeToken"
    SONARQUBE_ENDPOINT: "SonarQubeEndpoint"

phases:
  install:
    commands:
      - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
      - unzip sonar-scanner-cli-3.0.3.778-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.0.3.778-linux/bin/
  build:
    commands:
      - sonar-scanner
